# Generated by Django 5.0 on 2024-01-28 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('identifiant_unique', models.AutoField(primary_key=True, serialize=False)),
                ('nom_departement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medcin',
            fields=[
                ('identifiantunique', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('specialisation', models.CharField(max_length=100)),
                ('numero_licence', models.CharField(max_length=15, unique=True)),
                ('numero_telephone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('identifiantunique', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('adresse', models.CharField(max_length=255)),
                ('numero_telephone', models.IntegerField(max_length=10)),
                ('assurance_maladie', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinique',
            fields=[
                ('identifiant_unique', models.AutoField(primary_key=True, serialize=False)),
                ('nom_clinique', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('numero_telephone', models.IntegerField(max_length=10)),
                ('departements', models.ManyToManyField(related_name='cliniques', to='app1.departement')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='chef_departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.medcin'),
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('identifiantunique', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateField()),
                ('motif_consultation', models.TextField()),
                ('antecedents_medicaux', models.TextField()),
                ('resultats_examens', models.TextField()),
                ('diagnostic', models.TextField()),
                ('traitement_prescrit', models.TextField()),
                ('evolution_sante', models.TextField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.departement')),
                ('medcin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.medcin')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('identifiantunique', models.AutoField(primary_key=True, serialize=False)),
                ('date_consultation', models.DateField()),
                ('motif_consultation', models.TextField()),
                ('notes_consultation', models.TextField()),
                ('medcin_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.medcin')),
                ('pateint_consultee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('identifiantunique', models.AutoField(primary_key=True, serialize=False)),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('motif_rdv', models.TextField()),
                ('statut', models.CharField(choices=[('C', 'Confirmé'), ('A', 'Annulé'), ('EA', 'En attente'), ('R', 'Reprogrammé'), ('EC', 'En cours'), ('T', 'Terminé')], max_length=20)),
                ('medcin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.medcin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('identifiantunique', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateField()),
                ('date_echeance', models.DateField()),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('A', 'A faire'), ('E', 'En cours'), ('T', 'Terminé')], max_length=20)),
                ('priorite', models.CharField(choices=[('F', 'Faible'), ('M', 'Moyenne'), ('E', 'Elevée')], max_length=20)),
                ('dossier_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dossiermedical')),
                ('medcin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.medcin')),
            ],
        ),
    ]
